### ISSUE TITLE
Make `Warning.process(/foo/) { :raise }` fail on initial call

### ISSUE THREAD

**Issue by splattael** [jeremyevans/ruby-warning#17]
## Problem

I was wondering if `Warning.process(/foo/) { :raise }` is explicitly supported as it works only if no prior calls to `Warning.process` has been made.

Consider this code:

```ruby
require 'warning'

Warning.process(/foo/) { :raise } # This works?
Warning.process(/bar/) { :raise }
# => ArgumentError (comparison of Regexp with Regexp failed)
```

The first argument of [Warning.process](https://github.com/jeremyevans/ruby-warning/blob/32e5cfebf071122a945f67c3e1650fa97a4401bd/lib/warning.rb#L146) must be a path and actions can be passed as a Hash:

```ruby
require 'warning'

Warning.process('', /foo/ => :raise)
Warning.process('', /bar/ => :raise)
warn("foo") # => RuntimeError (foo)
warn("bar") # => RuntimeError (bar)
```

## Proposed solution

Make `Warning.process(/foo/) { :raise }` always fail.

Happy to create a PR if the proposed solution is accepted :muscle: 

## Refs

Refs https://gitlab.com/gitlab-org/gitlab/-/merge_requests/91789

**Comment by jeremyevans** [comment]
Thanks for the report. `Warning.process(regexp)` is not supported.  It ends up working by accident because when only a single element is in the process array, `sort_by!` does not raise.  We cannot support both regexps and strings as the path argument, because the algorithm used needs the paths sorted.

I'm generally against defensive programming type checks in Ruby, but I'm OK with a type check in this case.  Can you work on a PR for this?
