### ISSUE TITLE
Bundler and `Gem.path`

### ISSUE THREAD

**Issue by AlexWayfer** [jeremyevans/ruby-warning#8]
Hello.

I'm working on a project with the Sequel.

When I'm running `rspec --warnings` — there are too many warnings.

I saw that they're expected in Sequel: https://github.com/jeremyevans/sequel/issues/1184

And I saw their suppression in Sequel's specs: https://github.com/jeremyevans/sequel/blob/eeeb339/spec/sequel_warning.rb

So, I've tried to move this suppression into my project, specifically for Sequel.

But… `Warning.ignore` only accepts Strings as `path`, and only start-strings: https://github.com/jeremyevans/ruby-warning/blob/e2195ab/lib/warning.rb#L190

So, I can't use something like `/lib/sequel/` as `path` value.

OK, I saw `Gem.path.each` in the README: https://github.com/jeremyevans/ruby-warning/blob/e2195ab/README.rdoc

But… the problem is when I use `Gemfile` with `gem 'sequel', path: 'some/local/path/to/sequel'` — this path is not in `Gem.path` even with `bundle exec`.

So… maybe we should make `path` argument for `ignore` more flexible? Like, Regexp.

**Comment by jeremyevans** [comment]
I don't think we need to make the path more flexible.  I think doing so is a bad idea because doing so would confuse the warning prefix (the path where the warning occurs) with the warning message.

You just need to figure out a way for Bundler to tell you the path to use, similar to how `Gem.path` works when using gems.  Maybe `Bundler.home.to_s`?  I'm not sure exactly what is needed, I very rarely use bundler, and even in the cases I do, I just use it to load specific versions of gems installed via rubygems.

Additionally, I assume if you are passing `path: 'some/local/path/to/sequel'` in your `Gemfile`, you can use `Warning.ignore([:missing_ivar, :method_redefined, :not_reached], 'some/local/path/to/sequel')`. Can you try that and see if it works for you?

**Comment by AlexWayfer** [comment]
> I don't think we need to make the path more flexible. I think doing so is a bad idea because doing so would confuse the warning prefix (the path where the warning occurs) with the warning message.

OK, then I'm going to close this issue.

> You just need to figure out a way for Bundler to tell you the path to use, similar to how `Gem.path` works when using gems. Maybe `Bundler.home.to_s`? I'm not sure exactly what is needed, I very rarely use bundler, and even in the cases I do, I just use it to load specific versions of gems installed via rubygems.

I don't think so, because there is a home of Bundle, of course, but you can specify some gems differently. For example, you have `gem 'minitest'`, `gem 'foo_bar', github: 'AlexWayfer/foo_bar'` and `gem 'sequel', path: '../sequel'` (relatively to the directory of a project). So… I didn't find there something like `Bundler.gem('sequel').path`, but OK, I'll try to resolve it on that side.



> Additionally, I assume if you are passing `path: 'some/local/path/to/sequel'` in your `Gemfile`, you can use `Warning.ignore([:missing_ivar, :method_redefined, :not_reached], 'some/local/path/to/sequel')`. Can you try that and see if it works for you?

Yes, it should works. But it's a code duplication, not too good for me. Like, `:path` is commonly used for debugging something temporarily. So, if you have `gem 'sequel'` — you're using one path (`Gem.path` is acceptable in this case with Bundler, as I found). Then you can switch to `github: 'AlexWayfer/sequel', branch: 'pr1'` for something, there will be another path (I didn't check if `Gem.path` is acceptable here). And you can test something locally, before creating PR and other stuff, via `path: 'some/local/sequel'`, and you need to change a path for `Warning.ignore` with switching this. I know, it's a not a nightmare, but I'd like to avoid it.
